spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}

  jpa:
#    hibernate.ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  username: ${APP_USERNAME}
  password: ${APP_PASSWORD}

leaderboard:
  max-entries: 50
