name: Fly Deploy
on: [workflow_dispatch]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@master
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: mvn clean install package

      - run: flyctl deploy --config ./fly.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
