name: Fly Deploy
on: [workflow_dispatch]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: ./mvnw package

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --config ./fly.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}